class _BotCommands:
    def __init__(self):
        self.StartCommand = 'startb'
        self.MirrorCommand = 'mirrorb'
        self.UnzipMirrorCommand = 'unzipb'
        self.TarMirrorCommand = 'tarmirrorb'
        self.CancelMirror = 'cancelb'
        self.CancelAllCommand = 'cancelallb'
        self.ListCommand = 'listb'
        self.deleteCommand = 'deleteb'
        self.StatusCommand = 'statusb'
        self.AuthorizedUsersCommand = 'usersb'
        self.AuthorizeCommand = 'authorizeb'
        self.UnAuthorizeCommand = 'unauthb'
        self.AddSudoCommand = 'addsudob'
        self.RmSudoCommand = 'rmsudob'
        self.PingCommand = 'pingb'
        self.RestartCommand = 'restartb'
        self.StatsCommand = 'statsb'
        self.HelpCommand = 'helpb'
        self.LogCommand = 'logb'
        self.CloneCommand = 'cloneb'
        self.WatchCommand = 'ytb'
        self.TarWatchCommand = 'tarytb'
BotCommands = _BotCommands()
